version: '3'

services:
  web_marcaciones:
    image: nginx:stable-alpine3.21-perl
    restart: always
    container_name: web_marcaciones
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - red-gane-int

  api_marcaciones:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-marcaciones
    restart: always
    image: api-marca-v1.0
    networks:
      - red-gane-int
    environment:
      - TZ=America/Bogota
      
networks:
  red-gane-int:
    external: true
